name: Deploy to ECR

on:
  push:
    branches:
      - main  # This will trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          # Get the repository URI and define image tag
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
          REPOSITORY_URI=${{ secrets.ECR_REPOSITORY }}
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .

      # Step 4: Push the Docker image to ECR
      #comment
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
          REPOSITORY_URI=${{ secrets.ECR_REPOSITORY }}
          docker push $REPOSITORY_URI:$IMAGE_TAG
        
    
